import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/section/header";

import styles from "./layout.module.css";
import LeftSidebar from "@/components/section/left-sidebar";
import RightSidebar from "@/components/section/right-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className={styles.layout}>
          <LeftSidebar />
          <main className={styles.main}>
            <div className={styles.children}>
              {children}
              <RightSidebar />
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
