import type { Metadata } from "next";
import "./globals.css";

import styles from "./layout.module.css";
import LeftSidebar from "@/components/section/left-sidebar";
import RightSidebar from "@/components/section/right-sidebar";
import PrimarySearchAppBar from "@/components/ui/app-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.appbar}>
          <PrimarySearchAppBar />
        </div>
        <div className={styles.layout}>
          <LeftSidebar />
          <main className={styles.main}>
            <div className={styles.children}>{children}</div>
            <div className={styles.right_sidebar}>
              <RightSidebar />
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
