import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/section/header";
import SideBar from "@/components/section/sidebar";

import styles from './layout.module.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className={styles.layout}>

        <SideBar />
        <main>{children}</main>
        </div>

      </body>
    </html>
  );
}
